version: '2'

services:
  postgres:
    image: postgres:latest
    container_name: ${DC_PREFIX}-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    shm_size: '2gb'
    volumes:
      - ${BACKEND}/pgdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432

networks:
  default:
    external:
      name: ${DC_NETWORK}
